IF EXISTS (select * FROM sys.views where name = 'US_USER_INFO')
BEGIN
	DROP VIEW US_USER_INFO
END
GO

CREATE VIEW US_USER_INFO
AS 
SELECT ID, FIRST_NAME, LAST_NAME, COUNTRY, EMAIL_ADDRESS, LOGIN, PASSWORD, STATUS, CREATED_BY, CREATED_DATE, MAINTAINED_BY, MAINTAINED_DATE, VERSION 
  FROM USER_INFO 
 WHERE COUNTRY = 'US'
